### ISSUE TITLE
Mobile responsive needs some work

### ISSUE THREAD

**Issue by Nobiuss** [AppSaloon/condolence-manager#5]
Hi Team, 

We installed the version 2.8.0 with the default theme twentytwenty.
The responsive css is there but it needs some extra work.
As you can see in the screenshot, the "with: 120rem", it's better to use with: 100%.

What do you think?

![image (20)](https://user-images.githubusercontent.com/28691640/96256341-c3e69600-0fb8-11eb-92e9-ac58a7d515c5.png)

Kind regards, 
Kim Vanrijckel

**Comment by Mark-Creeten** [comment]
@Nobiuss & cedriekvos  if you want to replace width: 120rem with width: 100%, you also need to remove the max-width declaration, otherwise 100% has no meaning, & i see the declaration is based on a <div> element, those elements always are 100% (because block element), so you could leave out the all css rule related to width & mx-width
